spring:
  datasource:
    url: jdbc:mysql://localhost/sj_debug
    username: root
    password: sj_debug
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 10MB

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

logging.level:
  org.hibernate:
    SQL: debug
    type: trace

my-app:
  image:
    dir: '/Users/jody/Desktop/debug-backend/image/'

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

ai-server:
  schema: http
  host: 6b79-104-199-160-240.ngrok.io
  port: ~
  issue-detection:
    path: /detect-issue